name = "quadra-pharma-erp"
main = "worker.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "quadra-erp-db"
database_id = "REPLACE_WITH_YOUR_D1_ID"

[site]
bucket = "./"
